[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anonyme_transfer = "A26JcC1bfDZ1wV5Vkdo4rrwDcUzorjT55a6RGp7bAfzx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/home/wesker/Desktop/backend-stealf/artifacts/arcium_program_0.3.0.so"

[test.validator]
[[test.genesis]]
address = "Bv3Fb9VjzjWGfX18QTUcVycAfeLoQ5zZN6vv2g3cTZxp"
program = "/home/backend-stealf/artifacts/arcium_program_0.4.0.so"
